[versions]
ant = "1.10.14"
byte-buddy = "1.14.19"
fitlibrary = "20070619"
#fitlibrary = "20080702"
#fitlibrary = "20080812"
httpunit = "1.7.3"
jmock = "2.13.1"
junit-jupiter = "5.11.0"
log4j = "2.23.1"
oro = "2.0.8"
saxon-he = "12.5"

[libraries]
ant = { module = "org.apache.ant:ant", version.ref = "ant" }
byte-buddy = { module = "net.bytebuddy:byte-buddy", version.ref = "byte-buddy" }
fitlibrary = { module = "org.fitnesse:fitlibrary", version.ref = "fitlibrary" }
httpunit = { module = "org.httpunit:httpunit", version.ref = "httpunit" }
jmock-imposters = { module = "org.jmock:jmock-imposters", version.ref = "jmock" }
jmock-junit3 = { module = "org.jmock:jmock-junit3", version.ref = "jmock" }
jmock-junit4 = { module = "org.jmock:jmock-junit4", version.ref = "jmock" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
log4j-api = { module = "org.apache.logging.log4j:log4j-api", version.ref = "log4j" }
log4j-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }
oro = { module = "oro:oro", version.ref = "oro" }
saxon-he = { module = "net.sf.saxon:Saxon-HE", version.ref = "saxon-he" }

[bundles]
jmock = ["byte-buddy", "jmock-junit3", "jmock-junit4", "jmock-imposters"]
