name: Update Journal

on:
  push:
    branches: [gh-pages]
    paths: [data/Journal_*.txt]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.head_commit.id }}
      - name: Set up Journal generator
        run: |
          ln -s ${{ github.workspace }}/cgi-bin/data2html.cgi ${{ github.workspace }}/cgi-bin/Journal.cgi
          ls -al cgi-bin
      - name: Generate Journal
        run: |
          ${{ github.workspace }}/cgi-bin/Journal.cgi --no-headers > ${{ github.workspace }}/cgi-bin/Journal.html
          ls -al cgi-bin
      - name: Store Journal
        uses: actions/upload-artifact@v3
        with:
          name: Journal
          path: ${{ github.workspace }}/cgi-bin/Journal.html
